/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    offers: Offer;
    markets: Market;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: 'ar' | 'en' | 'tr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * خدمات M Creative — تظهر في صفحة الخدمات وفي معاينة الصفحة الرئيسية
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  description: string;
  icon?: ('strategy' | 'identity' | 'visual' | 'marketing') | null;
  /**
   * ترتيب الظهور — الأصغر يظهر أولاً
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * عروض M Creative — تظهر في صفحة العروض وفي معاينة الصفحة الرئيسية
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  /**
   * مثال: 01 — نفس القيمة بكل اللغات
   */
  index: string;
  title: string;
  whatBuys: string;
  scopeNote: string;
  /**
   * ترتيب الظهور — الأصغر يظهر أولاً
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * خارطة الأسواق التي تعمل بها M Creative — تظهر في صفحة الأسواق
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: string;
  /**
   * مثال: البداية
   */
  stage: string;
  title: string;
  description: string;
  /**
   * ترتيب الظهور — الأصغر يظهر أولاً
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * المشاريع المنفذة — كل مشروع له صفحة تفصيلية خاصة به
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * يُستخدم في رابط صفحة المشروع — نفس الرابط بكل اللغات. أحرف لاتينية وشرطات فقط، مثال: hzaya-brand
   */
  slug: string;
  /**
   * اسم العميل (اختياري) — نفس القيمة بكل اللغات
   */
  client?: string | null;
  /**
   * مثال: هوية بصرية، تسويق رقمي
   */
  category?: string | null;
  /**
   * يظهر في بطاقة المشروع بقائمة المشاريع
   */
  summary: string;
  /**
   * يظهر في صفحة المشروع التفصيلية
   */
  description: string;
  coverImage: string | Media;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * نفس أعضاء الفريق بكل اللغات — فقط المسمى الوظيفي (role) يُترجم
   */
  team?:
    | {
        /**
         * الاسم — نفس القيمة بكل اللغات
         */
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * يظهر في معاينة المشاريع بالصفحة الرئيسية
   */
  featured?: boolean | null;
  /**
   * ترتيب الظهور — الأصغر يظهر أولاً
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'markets';
        value: string | Market;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  index?: T;
  title?: T;
  whatBuys?: T;
  scopeNote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  stage?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  category?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * اسم الشركة، بيانات التواصل، وروابط التواصل الاجتماعي
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  contact?: {
    /**
     * البريد المستخدم في نموذج التواصل
     */
    email?: string | null;
    /**
     * رقم واتساب مع رمز الدولة، بدون علامة + أو مسافات — مثال: 905xxxxxxxxx
     */
    whatsapp?: string | null;
  };
  socials?: {
    /**
     * رابط كامل — مثال: https://instagram.com/mcreative
     */
    instagram?: string | null;
    /**
     * رابط كامل — مثال: https://linkedin.com/company/mcreative
     */
    linkedin?: string | null;
  };
  nav?:
    | {
        label: string;
        /**
         * مثال: /services — بدون بادئة اللغة، تُضاف تلقائياً
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * نص حقوق النشر — سيتم إلحاق السنة تلقائياً
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * محتوى المقدمة والموقف السعري فقط — الخدمات والعروض والأسواق ومشاريعنا لها أقسام (Collections) منفصلة، ومن نحن لها صفحة منفصلة
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  hero?: {
    kicker?: string | null;
    /**
     * اسم العلامة — نفس القيمة بكل اللغات عادةً
     */
    title?: string | null;
    englishTagline?: string | null;
    subtitleLine1?: string | null;
    subtitleLine2?: string | null;
    /**
     * صورة/بانر المقدمة — اتركه فارغاً لعدم عرض صورة
     */
    visual?: (string | null) | Media;
  };
  statement?: {
    quote?: string | null;
    highlight?: string | null;
    cite?: string | null;
  };
  footerAbout?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * محتوى صفحة "من نحن" التفصيلية — القصة، منهج العمل، والمؤسسون
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * فقرة أو أكثر — استخدم سطراً فارغاً للفصل بين الفقرات
   */
  story: string;
  processIntro?: {
    title?: string | null;
    description?: string | null;
  };
  process?:
    | {
        /**
         * مثال: قبل التنفيذ
         */
        stepLabel: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  founders?:
    | {
        /**
         * الاسم — نفس القيمة بكل اللغات
         */
        name: string;
        role: string;
        /**
         * نبذة مختصرة (اختياري)
         */
        bio?: string | null;
        photo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  contact?:
    | T
    | {
        email?: T;
        whatsapp?: T;
      };
  socials?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        englishTagline?: T;
        subtitleLine1?: T;
        subtitleLine2?: T;
        visual?: T;
      };
  statement?:
    | T
    | {
        quote?: T;
        highlight?: T;
        cite?: T;
      };
  footerAbout?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  story?: T;
  processIntro?:
    | T
    | {
        title?: T;
        description?: T;
      };
  process?:
    | T
    | {
        stepLabel?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  founders?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}